reboot:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "octopusnet"
          entity:
            domain: "sensor"

epg_scan:
  fields:
    device_id:
      required: true
      selector:
        device:
          multiple: true
          filter:
            integration: "octopusnet"
          entity:
            domain: "sensor"
